// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Authentication/authentication.proto

package ir.AralStudio.snapp.Grpc.AuthGrpcServices;

public final class AuthImplementation {
  private AuthImplementation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthService_Credentials_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthService_Credentials_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthService_Token_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthService_Token_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthService_user_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthService_user_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthService_driver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthService_driver_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)proto/Authentication/authentication.pr" +
      "oto\022\013AuthService\".\n\013Credentials\022\r\n\005phone" +
      "\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\026\n\005Token\022\r\n\005tok" +
      "en\030\001 \001(\t\"T\n\004user\022\r\n\005phone\030\001 \001(\t\022+\n\016drive" +
      "r_details\030\002 \001(\0132\023.AuthService.driver\022\020\n\010" +
      "password\030\003 \001(\t\"b\n\006driver\022\014\n\004name\030\001 \001(\t\022\020" +
      "\n\010lastname\030\002 \001(\t\022\022\n\nvehicle_no\030\003 \001(\t\022\017\n\007" +
      "balance\030\004 \001(\r\022\023\n\013profile_pic\030\005 \001(\t2y\n\004Au" +
      "th\022<\n\014Authenticate\022\030.AuthService.Credent" +
      "ials\032\022.AuthService.Token\0223\n\nNewAccount\022\021" +
      ".AuthService.user\032\022.AuthService.TokenBQ\n" +
      ")ir.AralStudio.snapp.Grpc.AuthGrpcServic" +
      "esB\022AuthImplementationP\001Z\016./GrpcServices" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AuthService_Credentials_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AuthService_Credentials_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthService_Credentials_descriptor,
        new java.lang.String[] { "Phone", "Password", });
    internal_static_AuthService_Token_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AuthService_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthService_Token_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_AuthService_user_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AuthService_user_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthService_user_descriptor,
        new java.lang.String[] { "Phone", "DriverDetails", "Password", });
    internal_static_AuthService_driver_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AuthService_driver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthService_driver_descriptor,
        new java.lang.String[] { "Name", "Lastname", "VehicleNo", "Balance", "ProfilePic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
