// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Authentication/authentication.proto

package ir.AralStudio.snapp.Grpc.AuthGrpcServices;

public interface CredentialsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthService.Credentials)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone = 1;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 1;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
