// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Authentication/authentication.proto

package ir.AralStudio.snapp.Grpc.AuthGrpcServices;

public interface userOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthService.user)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone = 1;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 1;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>.AuthService.driver driver_details = 2;</code>
   * @return Whether the driverDetails field is set.
   */
  boolean hasDriverDetails();
  /**
   * <code>.AuthService.driver driver_details = 2;</code>
   * @return The driverDetails.
   */
  ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver getDriverDetails();
  /**
   * <code>.AuthService.driver driver_details = 2;</code>
   */
  ir.AralStudio.snapp.Grpc.AuthGrpcServices.driverOrBuilder getDriverDetailsOrBuilder();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
