// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Authentication/authentication.proto

package ir.AralStudio.snapp.Grpc.AuthGrpcServices;

/**
 * Protobuf type {@code AuthService.user}
 */
public final class user extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AuthService.user)
    userOrBuilder {
private static final long serialVersionUID = 0L;
  // Use user.newBuilder() to construct.
  private user(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private user() {
    phone_ = "";
    password_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new user();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private user(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            phone_ = s;
            break;
          }
          case 18: {
            ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.Builder subBuilder = null;
            if (driverDetails_ != null) {
              subBuilder = driverDetails_.toBuilder();
            }
            driverDetails_ = input.readMessage(ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(driverDetails_);
              driverDetails_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ir.AralStudio.snapp.Grpc.AuthGrpcServices.AuthImplementation.internal_static_AuthService_user_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ir.AralStudio.snapp.Grpc.AuthGrpcServices.AuthImplementation.internal_static_AuthService_user_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ir.AralStudio.snapp.Grpc.AuthGrpcServices.user.class, ir.AralStudio.snapp.Grpc.AuthGrpcServices.user.Builder.class);
  }

  public static final int PHONE_FIELD_NUMBER = 1;
  private volatile java.lang.Object phone_;
  /**
   * <code>string phone = 1;</code>
   * @return The phone.
   */
  @java.lang.Override
  public java.lang.String getPhone() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phone_ = s;
      return s;
    }
  }
  /**
   * <code>string phone = 1;</code>
   * @return The bytes for phone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneBytes() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DRIVER_DETAILS_FIELD_NUMBER = 2;
  private ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver driverDetails_;
  /**
   * <code>.AuthService.driver driver_details = 2;</code>
   * @return Whether the driverDetails field is set.
   */
  @java.lang.Override
  public boolean hasDriverDetails() {
    return driverDetails_ != null;
  }
  /**
   * <code>.AuthService.driver driver_details = 2;</code>
   * @return The driverDetails.
   */
  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver getDriverDetails() {
    return driverDetails_ == null ? ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.getDefaultInstance() : driverDetails_;
  }
  /**
   * <code>.AuthService.driver driver_details = 2;</code>
   */
  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.AuthGrpcServices.driverOrBuilder getDriverDetailsOrBuilder() {
    return getDriverDetails();
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phone_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, phone_);
    }
    if (driverDetails_ != null) {
      output.writeMessage(2, getDriverDetails());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phone_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, phone_);
    }
    if (driverDetails_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDriverDetails());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ir.AralStudio.snapp.Grpc.AuthGrpcServices.user)) {
      return super.equals(obj);
    }
    ir.AralStudio.snapp.Grpc.AuthGrpcServices.user other = (ir.AralStudio.snapp.Grpc.AuthGrpcServices.user) obj;

    if (!getPhone()
        .equals(other.getPhone())) return false;
    if (hasDriverDetails() != other.hasDriverDetails()) return false;
    if (hasDriverDetails()) {
      if (!getDriverDetails()
          .equals(other.getDriverDetails())) return false;
    }
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PHONE_FIELD_NUMBER;
    hash = (53 * hash) + getPhone().hashCode();
    if (hasDriverDetails()) {
      hash = (37 * hash) + DRIVER_DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getDriverDetails().hashCode();
    }
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.AralStudio.snapp.Grpc.AuthGrpcServices.user prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AuthService.user}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AuthService.user)
      ir.AralStudio.snapp.Grpc.AuthGrpcServices.userOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.AralStudio.snapp.Grpc.AuthGrpcServices.AuthImplementation.internal_static_AuthService_user_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.AralStudio.snapp.Grpc.AuthGrpcServices.AuthImplementation.internal_static_AuthService_user_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.AralStudio.snapp.Grpc.AuthGrpcServices.user.class, ir.AralStudio.snapp.Grpc.AuthGrpcServices.user.Builder.class);
    }

    // Construct using ir.AralStudio.snapp.Grpc.AuthGrpcServices.user.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      phone_ = "";

      if (driverDetailsBuilder_ == null) {
        driverDetails_ = null;
      } else {
        driverDetails_ = null;
        driverDetailsBuilder_ = null;
      }
      password_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ir.AralStudio.snapp.Grpc.AuthGrpcServices.AuthImplementation.internal_static_AuthService_user_descriptor;
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.AuthGrpcServices.user getDefaultInstanceForType() {
      return ir.AralStudio.snapp.Grpc.AuthGrpcServices.user.getDefaultInstance();
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.AuthGrpcServices.user build() {
      ir.AralStudio.snapp.Grpc.AuthGrpcServices.user result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.AuthGrpcServices.user buildPartial() {
      ir.AralStudio.snapp.Grpc.AuthGrpcServices.user result = new ir.AralStudio.snapp.Grpc.AuthGrpcServices.user(this);
      result.phone_ = phone_;
      if (driverDetailsBuilder_ == null) {
        result.driverDetails_ = driverDetails_;
      } else {
        result.driverDetails_ = driverDetailsBuilder_.build();
      }
      result.password_ = password_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ir.AralStudio.snapp.Grpc.AuthGrpcServices.user) {
        return mergeFrom((ir.AralStudio.snapp.Grpc.AuthGrpcServices.user)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ir.AralStudio.snapp.Grpc.AuthGrpcServices.user other) {
      if (other == ir.AralStudio.snapp.Grpc.AuthGrpcServices.user.getDefaultInstance()) return this;
      if (!other.getPhone().isEmpty()) {
        phone_ = other.phone_;
        onChanged();
      }
      if (other.hasDriverDetails()) {
        mergeDriverDetails(other.getDriverDetails());
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ir.AralStudio.snapp.Grpc.AuthGrpcServices.user parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ir.AralStudio.snapp.Grpc.AuthGrpcServices.user) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object phone_ = "";
    /**
     * <code>string phone = 1;</code>
     * @return The phone.
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string phone = 1;</code>
     * @return The bytes for phone.
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string phone = 1;</code>
     * @param value The phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhone(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      phone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string phone = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone() {
      
      phone_ = getDefaultInstance().getPhone();
      onChanged();
      return this;
    }
    /**
     * <code>string phone = 1;</code>
     * @param value The bytes for phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      phone_ = value;
      onChanged();
      return this;
    }

    private ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver driverDetails_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver, ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.Builder, ir.AralStudio.snapp.Grpc.AuthGrpcServices.driverOrBuilder> driverDetailsBuilder_;
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     * @return Whether the driverDetails field is set.
     */
    public boolean hasDriverDetails() {
      return driverDetailsBuilder_ != null || driverDetails_ != null;
    }
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     * @return The driverDetails.
     */
    public ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver getDriverDetails() {
      if (driverDetailsBuilder_ == null) {
        return driverDetails_ == null ? ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.getDefaultInstance() : driverDetails_;
      } else {
        return driverDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     */
    public Builder setDriverDetails(ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver value) {
      if (driverDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        driverDetails_ = value;
        onChanged();
      } else {
        driverDetailsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     */
    public Builder setDriverDetails(
        ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.Builder builderForValue) {
      if (driverDetailsBuilder_ == null) {
        driverDetails_ = builderForValue.build();
        onChanged();
      } else {
        driverDetailsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     */
    public Builder mergeDriverDetails(ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver value) {
      if (driverDetailsBuilder_ == null) {
        if (driverDetails_ != null) {
          driverDetails_ =
            ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.newBuilder(driverDetails_).mergeFrom(value).buildPartial();
        } else {
          driverDetails_ = value;
        }
        onChanged();
      } else {
        driverDetailsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     */
    public Builder clearDriverDetails() {
      if (driverDetailsBuilder_ == null) {
        driverDetails_ = null;
        onChanged();
      } else {
        driverDetails_ = null;
        driverDetailsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     */
    public ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.Builder getDriverDetailsBuilder() {
      
      onChanged();
      return getDriverDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     */
    public ir.AralStudio.snapp.Grpc.AuthGrpcServices.driverOrBuilder getDriverDetailsOrBuilder() {
      if (driverDetailsBuilder_ != null) {
        return driverDetailsBuilder_.getMessageOrBuilder();
      } else {
        return driverDetails_ == null ?
            ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.getDefaultInstance() : driverDetails_;
      }
    }
    /**
     * <code>.AuthService.driver driver_details = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver, ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.Builder, ir.AralStudio.snapp.Grpc.AuthGrpcServices.driverOrBuilder> 
        getDriverDetailsFieldBuilder() {
      if (driverDetailsBuilder_ == null) {
        driverDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver, ir.AralStudio.snapp.Grpc.AuthGrpcServices.driver.Builder, ir.AralStudio.snapp.Grpc.AuthGrpcServices.driverOrBuilder>(
                getDriverDetails(),
                getParentForChildren(),
                isClean());
        driverDetails_ = null;
      }
      return driverDetailsBuilder_;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AuthService.user)
  }

  // @@protoc_insertion_point(class_scope:AuthService.user)
  private static final ir.AralStudio.snapp.Grpc.AuthGrpcServices.user DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ir.AralStudio.snapp.Grpc.AuthGrpcServices.user();
  }

  public static ir.AralStudio.snapp.Grpc.AuthGrpcServices.user getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<user>
      PARSER = new com.google.protobuf.AbstractParser<user>() {
    @java.lang.Override
    public user parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new user(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<user> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<user> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.AuthGrpcServices.user getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

