// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

public interface directionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelersService.direction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TravelersService.location origin = 1;</code>
   * @return Whether the origin field is set.
   */
  boolean hasOrigin();
  /**
   * <code>.TravelersService.location origin = 1;</code>
   * @return The origin.
   */
  ir.AralStudio.snapp.Grpc.TravelersService.location getOrigin();
  /**
   * <code>.TravelersService.location origin = 1;</code>
   */
  ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder getOriginOrBuilder();

  /**
   * <code>.TravelersService.location destination = 2;</code>
   * @return Whether the destination field is set.
   */
  boolean hasDestination();
  /**
   * <code>.TravelersService.location destination = 2;</code>
   * @return The destination.
   */
  ir.AralStudio.snapp.Grpc.TravelersService.location getDestination();
  /**
   * <code>.TravelersService.location destination = 2;</code>
   */
  ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder getDestinationOrBuilder();
}
