// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

/**
 * Protobuf type {@code TravelersService.direction}
 */
public final class direction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TravelersService.direction)
    directionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use direction.newBuilder() to construct.
  private direction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private direction() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new direction();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private direction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ir.AralStudio.snapp.Grpc.TravelersService.location.Builder subBuilder = null;
            if (origin_ != null) {
              subBuilder = origin_.toBuilder();
            }
            origin_ = input.readMessage(ir.AralStudio.snapp.Grpc.TravelersService.location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(origin_);
              origin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            ir.AralStudio.snapp.Grpc.TravelersService.location.Builder subBuilder = null;
            if (destination_ != null) {
              subBuilder = destination_.toBuilder();
            }
            destination_ = input.readMessage(ir.AralStudio.snapp.Grpc.TravelersService.location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(destination_);
              destination_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_direction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_direction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ir.AralStudio.snapp.Grpc.TravelersService.direction.class, ir.AralStudio.snapp.Grpc.TravelersService.direction.Builder.class);
  }

  public static final int ORIGIN_FIELD_NUMBER = 1;
  private ir.AralStudio.snapp.Grpc.TravelersService.location origin_;
  /**
   * <code>.TravelersService.location origin = 1;</code>
   * @return Whether the origin field is set.
   */
  @java.lang.Override
  public boolean hasOrigin() {
    return origin_ != null;
  }
  /**
   * <code>.TravelersService.location origin = 1;</code>
   * @return The origin.
   */
  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.location getOrigin() {
    return origin_ == null ? ir.AralStudio.snapp.Grpc.TravelersService.location.getDefaultInstance() : origin_;
  }
  /**
   * <code>.TravelersService.location origin = 1;</code>
   */
  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder getOriginOrBuilder() {
    return getOrigin();
  }

  public static final int DESTINATION_FIELD_NUMBER = 2;
  private ir.AralStudio.snapp.Grpc.TravelersService.location destination_;
  /**
   * <code>.TravelersService.location destination = 2;</code>
   * @return Whether the destination field is set.
   */
  @java.lang.Override
  public boolean hasDestination() {
    return destination_ != null;
  }
  /**
   * <code>.TravelersService.location destination = 2;</code>
   * @return The destination.
   */
  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.location getDestination() {
    return destination_ == null ? ir.AralStudio.snapp.Grpc.TravelersService.location.getDefaultInstance() : destination_;
  }
  /**
   * <code>.TravelersService.location destination = 2;</code>
   */
  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder getDestinationOrBuilder() {
    return getDestination();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (origin_ != null) {
      output.writeMessage(1, getOrigin());
    }
    if (destination_ != null) {
      output.writeMessage(2, getDestination());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (origin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOrigin());
    }
    if (destination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDestination());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ir.AralStudio.snapp.Grpc.TravelersService.direction)) {
      return super.equals(obj);
    }
    ir.AralStudio.snapp.Grpc.TravelersService.direction other = (ir.AralStudio.snapp.Grpc.TravelersService.direction) obj;

    if (hasOrigin() != other.hasOrigin()) return false;
    if (hasOrigin()) {
      if (!getOrigin()
          .equals(other.getOrigin())) return false;
    }
    if (hasDestination() != other.hasDestination()) return false;
    if (hasDestination()) {
      if (!getDestination()
          .equals(other.getDestination())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOrigin()) {
      hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getOrigin().hashCode();
    }
    if (hasDestination()) {
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.direction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.AralStudio.snapp.Grpc.TravelersService.direction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TravelersService.direction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TravelersService.direction)
      ir.AralStudio.snapp.Grpc.TravelersService.directionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_direction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_direction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.AralStudio.snapp.Grpc.TravelersService.direction.class, ir.AralStudio.snapp.Grpc.TravelersService.direction.Builder.class);
    }

    // Construct using ir.AralStudio.snapp.Grpc.TravelersService.direction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (originBuilder_ == null) {
        origin_ = null;
      } else {
        origin_ = null;
        originBuilder_ = null;
      }
      if (destinationBuilder_ == null) {
        destination_ = null;
      } else {
        destination_ = null;
        destinationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_direction_descriptor;
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.direction getDefaultInstanceForType() {
      return ir.AralStudio.snapp.Grpc.TravelersService.direction.getDefaultInstance();
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.direction build() {
      ir.AralStudio.snapp.Grpc.TravelersService.direction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.direction buildPartial() {
      ir.AralStudio.snapp.Grpc.TravelersService.direction result = new ir.AralStudio.snapp.Grpc.TravelersService.direction(this);
      if (originBuilder_ == null) {
        result.origin_ = origin_;
      } else {
        result.origin_ = originBuilder_.build();
      }
      if (destinationBuilder_ == null) {
        result.destination_ = destination_;
      } else {
        result.destination_ = destinationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ir.AralStudio.snapp.Grpc.TravelersService.direction) {
        return mergeFrom((ir.AralStudio.snapp.Grpc.TravelersService.direction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ir.AralStudio.snapp.Grpc.TravelersService.direction other) {
      if (other == ir.AralStudio.snapp.Grpc.TravelersService.direction.getDefaultInstance()) return this;
      if (other.hasOrigin()) {
        mergeOrigin(other.getOrigin());
      }
      if (other.hasDestination()) {
        mergeDestination(other.getDestination());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ir.AralStudio.snapp.Grpc.TravelersService.direction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ir.AralStudio.snapp.Grpc.TravelersService.direction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ir.AralStudio.snapp.Grpc.TravelersService.location origin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ir.AralStudio.snapp.Grpc.TravelersService.location, ir.AralStudio.snapp.Grpc.TravelersService.location.Builder, ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder> originBuilder_;
    /**
     * <code>.TravelersService.location origin = 1;</code>
     * @return Whether the origin field is set.
     */
    public boolean hasOrigin() {
      return originBuilder_ != null || origin_ != null;
    }
    /**
     * <code>.TravelersService.location origin = 1;</code>
     * @return The origin.
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.location getOrigin() {
      if (originBuilder_ == null) {
        return origin_ == null ? ir.AralStudio.snapp.Grpc.TravelersService.location.getDefaultInstance() : origin_;
      } else {
        return originBuilder_.getMessage();
      }
    }
    /**
     * <code>.TravelersService.location origin = 1;</code>
     */
    public Builder setOrigin(ir.AralStudio.snapp.Grpc.TravelersService.location value) {
      if (originBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        origin_ = value;
        onChanged();
      } else {
        originBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.TravelersService.location origin = 1;</code>
     */
    public Builder setOrigin(
        ir.AralStudio.snapp.Grpc.TravelersService.location.Builder builderForValue) {
      if (originBuilder_ == null) {
        origin_ = builderForValue.build();
        onChanged();
      } else {
        originBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.TravelersService.location origin = 1;</code>
     */
    public Builder mergeOrigin(ir.AralStudio.snapp.Grpc.TravelersService.location value) {
      if (originBuilder_ == null) {
        if (origin_ != null) {
          origin_ =
            ir.AralStudio.snapp.Grpc.TravelersService.location.newBuilder(origin_).mergeFrom(value).buildPartial();
        } else {
          origin_ = value;
        }
        onChanged();
      } else {
        originBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.TravelersService.location origin = 1;</code>
     */
    public Builder clearOrigin() {
      if (originBuilder_ == null) {
        origin_ = null;
        onChanged();
      } else {
        origin_ = null;
        originBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.TravelersService.location origin = 1;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.location.Builder getOriginBuilder() {
      
      onChanged();
      return getOriginFieldBuilder().getBuilder();
    }
    /**
     * <code>.TravelersService.location origin = 1;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder getOriginOrBuilder() {
      if (originBuilder_ != null) {
        return originBuilder_.getMessageOrBuilder();
      } else {
        return origin_ == null ?
            ir.AralStudio.snapp.Grpc.TravelersService.location.getDefaultInstance() : origin_;
      }
    }
    /**
     * <code>.TravelersService.location origin = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ir.AralStudio.snapp.Grpc.TravelersService.location, ir.AralStudio.snapp.Grpc.TravelersService.location.Builder, ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder> 
        getOriginFieldBuilder() {
      if (originBuilder_ == null) {
        originBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ir.AralStudio.snapp.Grpc.TravelersService.location, ir.AralStudio.snapp.Grpc.TravelersService.location.Builder, ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder>(
                getOrigin(),
                getParentForChildren(),
                isClean());
        origin_ = null;
      }
      return originBuilder_;
    }

    private ir.AralStudio.snapp.Grpc.TravelersService.location destination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ir.AralStudio.snapp.Grpc.TravelersService.location, ir.AralStudio.snapp.Grpc.TravelersService.location.Builder, ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder> destinationBuilder_;
    /**
     * <code>.TravelersService.location destination = 2;</code>
     * @return Whether the destination field is set.
     */
    public boolean hasDestination() {
      return destinationBuilder_ != null || destination_ != null;
    }
    /**
     * <code>.TravelersService.location destination = 2;</code>
     * @return The destination.
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.location getDestination() {
      if (destinationBuilder_ == null) {
        return destination_ == null ? ir.AralStudio.snapp.Grpc.TravelersService.location.getDefaultInstance() : destination_;
      } else {
        return destinationBuilder_.getMessage();
      }
    }
    /**
     * <code>.TravelersService.location destination = 2;</code>
     */
    public Builder setDestination(ir.AralStudio.snapp.Grpc.TravelersService.location value) {
      if (destinationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destination_ = value;
        onChanged();
      } else {
        destinationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.TravelersService.location destination = 2;</code>
     */
    public Builder setDestination(
        ir.AralStudio.snapp.Grpc.TravelersService.location.Builder builderForValue) {
      if (destinationBuilder_ == null) {
        destination_ = builderForValue.build();
        onChanged();
      } else {
        destinationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.TravelersService.location destination = 2;</code>
     */
    public Builder mergeDestination(ir.AralStudio.snapp.Grpc.TravelersService.location value) {
      if (destinationBuilder_ == null) {
        if (destination_ != null) {
          destination_ =
            ir.AralStudio.snapp.Grpc.TravelersService.location.newBuilder(destination_).mergeFrom(value).buildPartial();
        } else {
          destination_ = value;
        }
        onChanged();
      } else {
        destinationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.TravelersService.location destination = 2;</code>
     */
    public Builder clearDestination() {
      if (destinationBuilder_ == null) {
        destination_ = null;
        onChanged();
      } else {
        destination_ = null;
        destinationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.TravelersService.location destination = 2;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.location.Builder getDestinationBuilder() {
      
      onChanged();
      return getDestinationFieldBuilder().getBuilder();
    }
    /**
     * <code>.TravelersService.location destination = 2;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder getDestinationOrBuilder() {
      if (destinationBuilder_ != null) {
        return destinationBuilder_.getMessageOrBuilder();
      } else {
        return destination_ == null ?
            ir.AralStudio.snapp.Grpc.TravelersService.location.getDefaultInstance() : destination_;
      }
    }
    /**
     * <code>.TravelersService.location destination = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ir.AralStudio.snapp.Grpc.TravelersService.location, ir.AralStudio.snapp.Grpc.TravelersService.location.Builder, ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder> 
        getDestinationFieldBuilder() {
      if (destinationBuilder_ == null) {
        destinationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ir.AralStudio.snapp.Grpc.TravelersService.location, ir.AralStudio.snapp.Grpc.TravelersService.location.Builder, ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder>(
                getDestination(),
                getParentForChildren(),
                isClean());
        destination_ = null;
      }
      return destinationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TravelersService.direction)
  }

  // @@protoc_insertion_point(class_scope:TravelersService.direction)
  private static final ir.AralStudio.snapp.Grpc.TravelersService.direction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ir.AralStudio.snapp.Grpc.TravelersService.direction();
  }

  public static ir.AralStudio.snapp.Grpc.TravelersService.direction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<direction>
      PARSER = new com.google.protobuf.AbstractParser<direction>() {
    @java.lang.Override
    public direction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new direction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<direction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<direction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.direction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

