// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

public interface driverLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelersService.driverLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.TravelersService.location location = 2;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.TravelersService.location location = 2;</code>
   * @return The location.
   */
  ir.AralStudio.snapp.Grpc.TravelersService.location getLocation();
  /**
   * <code>.TravelersService.location location = 2;</code>
   */
  ir.AralStudio.snapp.Grpc.TravelersService.locationOrBuilder getLocationOrBuilder();
}
