// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

/**
 * Protobuf type {@code TravelersService.driver}
 */
public final class driver extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TravelersService.driver)
    driverOrBuilder {
private static final long serialVersionUID = 0L;
  // Use driver.newBuilder() to construct.
  private driver(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private driver() {
    id_ = "";
    name_ = "";
    lastname_ = "";
    vehicleNo_ = "";
    profilePic_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new driver();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private driver(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            lastname_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            vehicleNo_ = s;
            break;
          }
          case 40: {

            balance_ = input.readUInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            profilePic_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_driver_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_driver_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ir.AralStudio.snapp.Grpc.TravelersService.driver.class, ir.AralStudio.snapp.Grpc.TravelersService.driver.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object lastname_;
  /**
   * <code>string lastname = 3;</code>
   * @return The lastname.
   */
  @java.lang.Override
  public java.lang.String getLastname() {
    java.lang.Object ref = lastname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastname_ = s;
      return s;
    }
  }
  /**
   * <code>string lastname = 3;</code>
   * @return The bytes for lastname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastnameBytes() {
    java.lang.Object ref = lastname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VEHICLE_NO_FIELD_NUMBER = 4;
  private volatile java.lang.Object vehicleNo_;
  /**
   * <code>string vehicle_no = 4;</code>
   * @return The vehicleNo.
   */
  @java.lang.Override
  public java.lang.String getVehicleNo() {
    java.lang.Object ref = vehicleNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vehicleNo_ = s;
      return s;
    }
  }
  /**
   * <code>string vehicle_no = 4;</code>
   * @return The bytes for vehicleNo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVehicleNoBytes() {
    java.lang.Object ref = vehicleNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vehicleNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BALANCE_FIELD_NUMBER = 5;
  private int balance_;
  /**
   * <code>uint32 balance = 5;</code>
   * @return The balance.
   */
  @java.lang.Override
  public int getBalance() {
    return balance_;
  }

  public static final int PROFILE_PIC_FIELD_NUMBER = 6;
  private volatile java.lang.Object profilePic_;
  /**
   * <code>string profile_pic = 6;</code>
   * @return The profilePic.
   */
  @java.lang.Override
  public java.lang.String getProfilePic() {
    java.lang.Object ref = profilePic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      profilePic_ = s;
      return s;
    }
  }
  /**
   * <code>string profile_pic = 6;</code>
   * @return The bytes for profilePic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProfilePicBytes() {
    java.lang.Object ref = profilePic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profilePic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vehicleNo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, vehicleNo_);
    }
    if (balance_ != 0) {
      output.writeUInt32(5, balance_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(profilePic_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, profilePic_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vehicleNo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, vehicleNo_);
    }
    if (balance_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, balance_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(profilePic_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, profilePic_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ir.AralStudio.snapp.Grpc.TravelersService.driver)) {
      return super.equals(obj);
    }
    ir.AralStudio.snapp.Grpc.TravelersService.driver other = (ir.AralStudio.snapp.Grpc.TravelersService.driver) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getLastname()
        .equals(other.getLastname())) return false;
    if (!getVehicleNo()
        .equals(other.getVehicleNo())) return false;
    if (getBalance()
        != other.getBalance()) return false;
    if (!getProfilePic()
        .equals(other.getProfilePic())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastname().hashCode();
    hash = (37 * hash) + VEHICLE_NO_FIELD_NUMBER;
    hash = (53 * hash) + getVehicleNo().hashCode();
    hash = (37 * hash) + BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + getBalance();
    hash = (37 * hash) + PROFILE_PIC_FIELD_NUMBER;
    hash = (53 * hash) + getProfilePic().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.driver parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.AralStudio.snapp.Grpc.TravelersService.driver prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TravelersService.driver}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TravelersService.driver)
      ir.AralStudio.snapp.Grpc.TravelersService.driverOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_driver_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_driver_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.AralStudio.snapp.Grpc.TravelersService.driver.class, ir.AralStudio.snapp.Grpc.TravelersService.driver.Builder.class);
    }

    // Construct using ir.AralStudio.snapp.Grpc.TravelersService.driver.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      lastname_ = "";

      vehicleNo_ = "";

      balance_ = 0;

      profilePic_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_driver_descriptor;
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.driver getDefaultInstanceForType() {
      return ir.AralStudio.snapp.Grpc.TravelersService.driver.getDefaultInstance();
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.driver build() {
      ir.AralStudio.snapp.Grpc.TravelersService.driver result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.driver buildPartial() {
      ir.AralStudio.snapp.Grpc.TravelersService.driver result = new ir.AralStudio.snapp.Grpc.TravelersService.driver(this);
      result.id_ = id_;
      result.name_ = name_;
      result.lastname_ = lastname_;
      result.vehicleNo_ = vehicleNo_;
      result.balance_ = balance_;
      result.profilePic_ = profilePic_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ir.AralStudio.snapp.Grpc.TravelersService.driver) {
        return mergeFrom((ir.AralStudio.snapp.Grpc.TravelersService.driver)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ir.AralStudio.snapp.Grpc.TravelersService.driver other) {
      if (other == ir.AralStudio.snapp.Grpc.TravelersService.driver.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getLastname().isEmpty()) {
        lastname_ = other.lastname_;
        onChanged();
      }
      if (!other.getVehicleNo().isEmpty()) {
        vehicleNo_ = other.vehicleNo_;
        onChanged();
      }
      if (other.getBalance() != 0) {
        setBalance(other.getBalance());
      }
      if (!other.getProfilePic().isEmpty()) {
        profilePic_ = other.profilePic_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ir.AralStudio.snapp.Grpc.TravelersService.driver parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ir.AralStudio.snapp.Grpc.TravelersService.driver) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastname_ = "";
    /**
     * <code>string lastname = 3;</code>
     * @return The lastname.
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastname = 3;</code>
     * @return The bytes for lastname.
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastname = 3;</code>
     * @param value The lastname to set.
     * @return This builder for chaining.
     */
    public Builder setLastname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastname = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastname() {
      
      lastname_ = getDefaultInstance().getLastname();
      onChanged();
      return this;
    }
    /**
     * <code>string lastname = 3;</code>
     * @param value The bytes for lastname to set.
     * @return This builder for chaining.
     */
    public Builder setLastnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object vehicleNo_ = "";
    /**
     * <code>string vehicle_no = 4;</code>
     * @return The vehicleNo.
     */
    public java.lang.String getVehicleNo() {
      java.lang.Object ref = vehicleNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicleNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vehicle_no = 4;</code>
     * @return The bytes for vehicleNo.
     */
    public com.google.protobuf.ByteString
        getVehicleNoBytes() {
      java.lang.Object ref = vehicleNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vehicle_no = 4;</code>
     * @param value The vehicleNo to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vehicleNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vehicle_no = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVehicleNo() {
      
      vehicleNo_ = getDefaultInstance().getVehicleNo();
      onChanged();
      return this;
    }
    /**
     * <code>string vehicle_no = 4;</code>
     * @param value The bytes for vehicleNo to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vehicleNo_ = value;
      onChanged();
      return this;
    }

    private int balance_ ;
    /**
     * <code>uint32 balance = 5;</code>
     * @return The balance.
     */
    @java.lang.Override
    public int getBalance() {
      return balance_;
    }
    /**
     * <code>uint32 balance = 5;</code>
     * @param value The balance to set.
     * @return This builder for chaining.
     */
    public Builder setBalance(int value) {
      
      balance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 balance = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBalance() {
      
      balance_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object profilePic_ = "";
    /**
     * <code>string profile_pic = 6;</code>
     * @return The profilePic.
     */
    public java.lang.String getProfilePic() {
      java.lang.Object ref = profilePic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profilePic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string profile_pic = 6;</code>
     * @return The bytes for profilePic.
     */
    public com.google.protobuf.ByteString
        getProfilePicBytes() {
      java.lang.Object ref = profilePic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profilePic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string profile_pic = 6;</code>
     * @param value The profilePic to set.
     * @return This builder for chaining.
     */
    public Builder setProfilePic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      profilePic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string profile_pic = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfilePic() {
      
      profilePic_ = getDefaultInstance().getProfilePic();
      onChanged();
      return this;
    }
    /**
     * <code>string profile_pic = 6;</code>
     * @param value The bytes for profilePic to set.
     * @return This builder for chaining.
     */
    public Builder setProfilePicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      profilePic_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TravelersService.driver)
  }

  // @@protoc_insertion_point(class_scope:TravelersService.driver)
  private static final ir.AralStudio.snapp.Grpc.TravelersService.driver DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ir.AralStudio.snapp.Grpc.TravelersService.driver();
  }

  public static ir.AralStudio.snapp.Grpc.TravelersService.driver getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<driver>
      PARSER = new com.google.protobuf.AbstractParser<driver>() {
    @java.lang.Override
    public driver parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new driver(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<driver> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<driver> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.driver getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

