// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

/**
 * Protobuf type {@code TravelersService.GetNearbyDriversResponse}
 */
public final class GetNearbyDriversResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TravelersService.GetNearbyDriversResponse)
    GetNearbyDriversResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetNearbyDriversResponse.newBuilder() to construct.
  private GetNearbyDriversResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetNearbyDriversResponse() {
    driver_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetNearbyDriversResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetNearbyDriversResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              driver_ = new java.util.ArrayList<ir.AralStudio.snapp.Grpc.TravelersService.driverLocation>();
              mutable_bitField0_ |= 0x00000001;
            }
            driver_.add(
                input.readMessage(ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        driver_ = java.util.Collections.unmodifiableList(driver_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_GetNearbyDriversResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_GetNearbyDriversResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse.class, ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse.Builder.class);
  }

  public static final int DRIVER_FIELD_NUMBER = 1;
  private java.util.List<ir.AralStudio.snapp.Grpc.TravelersService.driverLocation> driver_;
  /**
   * <code>repeated .TravelersService.driverLocation driver = 1;</code>
   */
  @java.lang.Override
  public java.util.List<ir.AralStudio.snapp.Grpc.TravelersService.driverLocation> getDriverList() {
    return driver_;
  }
  /**
   * <code>repeated .TravelersService.driverLocation driver = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ir.AralStudio.snapp.Grpc.TravelersService.driverLocationOrBuilder> 
      getDriverOrBuilderList() {
    return driver_;
  }
  /**
   * <code>repeated .TravelersService.driverLocation driver = 1;</code>
   */
  @java.lang.Override
  public int getDriverCount() {
    return driver_.size();
  }
  /**
   * <code>repeated .TravelersService.driverLocation driver = 1;</code>
   */
  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.driverLocation getDriver(int index) {
    return driver_.get(index);
  }
  /**
   * <code>repeated .TravelersService.driverLocation driver = 1;</code>
   */
  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.driverLocationOrBuilder getDriverOrBuilder(
      int index) {
    return driver_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < driver_.size(); i++) {
      output.writeMessage(1, driver_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < driver_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, driver_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse)) {
      return super.equals(obj);
    }
    ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse other = (ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse) obj;

    if (!getDriverList()
        .equals(other.getDriverList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDriverCount() > 0) {
      hash = (37 * hash) + DRIVER_FIELD_NUMBER;
      hash = (53 * hash) + getDriverList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TravelersService.GetNearbyDriversResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TravelersService.GetNearbyDriversResponse)
      ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_GetNearbyDriversResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_GetNearbyDriversResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse.class, ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse.Builder.class);
    }

    // Construct using ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDriverFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (driverBuilder_ == null) {
        driver_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        driverBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ir.AralStudio.snapp.Grpc.TravelersService.TravelersServiceImplementation.internal_static_TravelersService_GetNearbyDriversResponse_descriptor;
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse getDefaultInstanceForType() {
      return ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse build() {
      ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse buildPartial() {
      ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse result = new ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse(this);
      int from_bitField0_ = bitField0_;
      if (driverBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          driver_ = java.util.Collections.unmodifiableList(driver_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.driver_ = driver_;
      } else {
        result.driver_ = driverBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse) {
        return mergeFrom((ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse other) {
      if (other == ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse.getDefaultInstance()) return this;
      if (driverBuilder_ == null) {
        if (!other.driver_.isEmpty()) {
          if (driver_.isEmpty()) {
            driver_ = other.driver_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDriverIsMutable();
            driver_.addAll(other.driver_);
          }
          onChanged();
        }
      } else {
        if (!other.driver_.isEmpty()) {
          if (driverBuilder_.isEmpty()) {
            driverBuilder_.dispose();
            driverBuilder_ = null;
            driver_ = other.driver_;
            bitField0_ = (bitField0_ & ~0x00000001);
            driverBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDriverFieldBuilder() : null;
          } else {
            driverBuilder_.addAllMessages(other.driver_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ir.AralStudio.snapp.Grpc.TravelersService.driverLocation> driver_ =
      java.util.Collections.emptyList();
    private void ensureDriverIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        driver_ = new java.util.ArrayList<ir.AralStudio.snapp.Grpc.TravelersService.driverLocation>(driver_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ir.AralStudio.snapp.Grpc.TravelersService.driverLocation, ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder, ir.AralStudio.snapp.Grpc.TravelersService.driverLocationOrBuilder> driverBuilder_;

    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public java.util.List<ir.AralStudio.snapp.Grpc.TravelersService.driverLocation> getDriverList() {
      if (driverBuilder_ == null) {
        return java.util.Collections.unmodifiableList(driver_);
      } else {
        return driverBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public int getDriverCount() {
      if (driverBuilder_ == null) {
        return driver_.size();
      } else {
        return driverBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.driverLocation getDriver(int index) {
      if (driverBuilder_ == null) {
        return driver_.get(index);
      } else {
        return driverBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder setDriver(
        int index, ir.AralStudio.snapp.Grpc.TravelersService.driverLocation value) {
      if (driverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDriverIsMutable();
        driver_.set(index, value);
        onChanged();
      } else {
        driverBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder setDriver(
        int index, ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder builderForValue) {
      if (driverBuilder_ == null) {
        ensureDriverIsMutable();
        driver_.set(index, builderForValue.build());
        onChanged();
      } else {
        driverBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder addDriver(ir.AralStudio.snapp.Grpc.TravelersService.driverLocation value) {
      if (driverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDriverIsMutable();
        driver_.add(value);
        onChanged();
      } else {
        driverBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder addDriver(
        int index, ir.AralStudio.snapp.Grpc.TravelersService.driverLocation value) {
      if (driverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDriverIsMutable();
        driver_.add(index, value);
        onChanged();
      } else {
        driverBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder addDriver(
        ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder builderForValue) {
      if (driverBuilder_ == null) {
        ensureDriverIsMutable();
        driver_.add(builderForValue.build());
        onChanged();
      } else {
        driverBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder addDriver(
        int index, ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder builderForValue) {
      if (driverBuilder_ == null) {
        ensureDriverIsMutable();
        driver_.add(index, builderForValue.build());
        onChanged();
      } else {
        driverBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder addAllDriver(
        java.lang.Iterable<? extends ir.AralStudio.snapp.Grpc.TravelersService.driverLocation> values) {
      if (driverBuilder_ == null) {
        ensureDriverIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, driver_);
        onChanged();
      } else {
        driverBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder clearDriver() {
      if (driverBuilder_ == null) {
        driver_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        driverBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public Builder removeDriver(int index) {
      if (driverBuilder_ == null) {
        ensureDriverIsMutable();
        driver_.remove(index);
        onChanged();
      } else {
        driverBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder getDriverBuilder(
        int index) {
      return getDriverFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.driverLocationOrBuilder getDriverOrBuilder(
        int index) {
      if (driverBuilder_ == null) {
        return driver_.get(index);  } else {
        return driverBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public java.util.List<? extends ir.AralStudio.snapp.Grpc.TravelersService.driverLocationOrBuilder> 
         getDriverOrBuilderList() {
      if (driverBuilder_ != null) {
        return driverBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(driver_);
      }
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder addDriverBuilder() {
      return getDriverFieldBuilder().addBuilder(
          ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.getDefaultInstance());
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder addDriverBuilder(
        int index) {
      return getDriverFieldBuilder().addBuilder(
          index, ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.getDefaultInstance());
    }
    /**
     * <code>repeated .TravelersService.driverLocation driver = 1;</code>
     */
    public java.util.List<ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder> 
         getDriverBuilderList() {
      return getDriverFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ir.AralStudio.snapp.Grpc.TravelersService.driverLocation, ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder, ir.AralStudio.snapp.Grpc.TravelersService.driverLocationOrBuilder> 
        getDriverFieldBuilder() {
      if (driverBuilder_ == null) {
        driverBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ir.AralStudio.snapp.Grpc.TravelersService.driverLocation, ir.AralStudio.snapp.Grpc.TravelersService.driverLocation.Builder, ir.AralStudio.snapp.Grpc.TravelersService.driverLocationOrBuilder>(
                driver_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        driver_ = null;
      }
      return driverBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TravelersService.GetNearbyDriversResponse)
  }

  // @@protoc_insertion_point(class_scope:TravelersService.GetNearbyDriversResponse)
  private static final ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse();
  }

  public static ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetNearbyDriversResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetNearbyDriversResponse>() {
    @java.lang.Override
    public GetNearbyDriversResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetNearbyDriversResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetNearbyDriversResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetNearbyDriversResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ir.AralStudio.snapp.Grpc.TravelersService.GetNearbyDriversResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

