// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

public interface locationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelersService.location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();
}
