// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

public interface priceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelersService.price)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 price = 1;</code>
   * @return The price.
   */
  int getPrice();
}
