// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

public final class TravelersServiceImplementation {
  private TravelersServiceImplementation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_GetNearbyDriversResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_GetNearbyDriversResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_driverLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_driverLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_driver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_driver_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-proto/TravelersService/TravelersServic" +
      "e.proto\022\020TravelersService\"L\n\030GetNearbyDr" +
      "iversResponse\0220\n\006driver\030\001 \003(\0132 .Traveler" +
      "sService.driverLocation\" \n\010location\022\t\n\001x" +
      "\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"J\n\016driverLocation\022\n\n\002i" +
      "d\030\001 \001(\t\022,\n\010location\030\002 \001(\0132\032.TravelersSer" +
      "vice.location\"b\n\006driver\022\014\n\004name\030\001 \001(\t\022\020\n" +
      "\010lastname\030\002 \001(\t\022\022\n\nvehicle_no\030\003 \001(\t\022\017\n\007b" +
      "alance\030\004 \001(\r\022\023\n\013profile_pic\030\005 \001(\t2n\n\020Tra" +
      "velersService\022Z\n\020GetNearbyDrivers\022\032.Trav" +
      "elersService.location\032*.TravelersService" +
      ".GetNearbyDriversResponseB]\n)ir.AralStud" +
      "io.snapp.Grpc.TravelersServiceB\036Traveler" +
      "sServiceImplementationP\001Z\016./GrpcServices" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TravelersService_GetNearbyDriversResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TravelersService_GetNearbyDriversResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_GetNearbyDriversResponse_descriptor,
        new java.lang.String[] { "Driver", });
    internal_static_TravelersService_location_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TravelersService_location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_location_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_TravelersService_driverLocation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TravelersService_driverLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_driverLocation_descriptor,
        new java.lang.String[] { "Id", "Location", });
    internal_static_TravelersService_driver_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TravelersService_driver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_driver_descriptor,
        new java.lang.String[] { "Name", "Lastname", "VehicleNo", "Balance", "ProfilePic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
