// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/TravelersService/TravelersService.proto

package ir.AralStudio.snapp.Grpc.TravelersService;

public final class TravelersServiceImplementation {
  private TravelersServiceImplementation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_GetNearbyDriversResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_GetNearbyDriversResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_direction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_direction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_price_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_price_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_driverLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_driverLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_driver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_driver_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-proto/TravelersService/TravelersServic" +
      "e.proto\022\020TravelersService\"L\n\030GetNearbyDr" +
      "iversResponse\0220\n\006driver\030\001 \003(\0132 .Traveler" +
      "sService.driverLocation\"h\n\tdirection\022*\n\006" +
      "origin\030\001 \001(\0132\032.TravelersService.location" +
      "\022/\n\013destination\030\002 \001(\0132\032.TravelersService" +
      ".location\"\026\n\005price\022\r\n\005price\030\001 \001(\005\" \n\010loc" +
      "ation\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"J\n\016driverLoc" +
      "ation\022\n\n\002id\030\001 \001(\t\022,\n\010location\030\002 \001(\0132\032.Tr" +
      "avelersService.location\"n\n\006driver\022\n\n\002id\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010lastname\030\003 \001(\t\022\022\n" +
      "\nvehicle_no\030\004 \001(\t\022\017\n\007balance\030\005 \001(\r\022\023\n\013pr" +
      "ofile_pic\030\006 \001(\t2\370\001\n\020TravelersService\022Z\n\020" +
      "GetNearbyDrivers\022\032.TravelersService.loca" +
      "tion\032*.TravelersService.GetNearbyDrivers" +
      "Response\022@\n\010GetPrice\022\033.TravelersService." +
      "direction\032\027.TravelersService.price\022F\n\rRe" +
      "questDriver\022\033.TravelersService.direction" +
      "\032\030.TravelersService.driverB]\n)ir.AralStu" +
      "dio.snapp.Grpc.TravelersServiceB\036Travele" +
      "rsServiceImplementationP\001Z\016./GrpcService" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TravelersService_GetNearbyDriversResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TravelersService_GetNearbyDriversResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_GetNearbyDriversResponse_descriptor,
        new java.lang.String[] { "Driver", });
    internal_static_TravelersService_direction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TravelersService_direction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_direction_descriptor,
        new java.lang.String[] { "Origin", "Destination", });
    internal_static_TravelersService_price_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TravelersService_price_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_price_descriptor,
        new java.lang.String[] { "Price", });
    internal_static_TravelersService_location_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TravelersService_location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_location_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_TravelersService_driverLocation_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_TravelersService_driverLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_driverLocation_descriptor,
        new java.lang.String[] { "Id", "Location", });
    internal_static_TravelersService_driver_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_TravelersService_driver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_driver_descriptor,
        new java.lang.String[] { "Id", "Name", "Lastname", "VehicleNo", "Balance", "ProfilePic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
