// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TravelersService.proto

package ir.AralStudio.snapp.Grpc.GrpcServices;

public interface GetNearbyDriversResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TravelersService.GetNearbyDriversResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TravelersService.user user = 1;</code>
   */
  java.util.List<ir.AralStudio.snapp.Grpc.GrpcServices.user> 
      getUserList();
  /**
   * <code>repeated .TravelersService.user user = 1;</code>
   */
  ir.AralStudio.snapp.Grpc.GrpcServices.user getUser(int index);
  /**
   * <code>repeated .TravelersService.user user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .TravelersService.user user = 1;</code>
   */
  java.util.List<? extends ir.AralStudio.snapp.Grpc.GrpcServices.userOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .TravelersService.user user = 1;</code>
   */
  ir.AralStudio.snapp.Grpc.GrpcServices.userOrBuilder getUserOrBuilder(
      int index);
}
