// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ir/AralStudio/snapp/Grpc/GrpcServices/TravelersService.proto

package ir.AralStudio.snapp.Grpc.GrpcServices;

public final class TravelersServiceImplementation {
  private TravelersServiceImplementation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_GetNearbyDriversResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_GetNearbyDriversResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_user_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_user_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TravelersService_driver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TravelersService_driver_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<ir/AralStudio/snapp/Grpc/GrpcServices/" +
      "TravelersService.proto\022\020TravelersService" +
      "\"@\n\030GetNearbyDriversResponse\022$\n\004user\030\001 \003" +
      "(\0132\026.TravelersService.user\" \n\010location\022\t" +
      "\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"D\n\004user\022\n\n\002id\030\001 \001(\t" +
      "\0220\n\016driver_details\030\002 \001(\0132\030.TravelersServ" +
      "ice.driver\"b\n\006driver\022\014\n\004name\030\001 \001(\t\022\020\n\010la" +
      "stname\030\002 \001(\t\022\022\n\nvehicle_no\030\003 \001(\t\022\017\n\007bala" +
      "nce\030\004 \001(\r\022\023\n\013profile_pic\030\005 \001(\t2n\n\020Travel" +
      "ersService\022Z\n\020GetNearbyDrivers\022\032.Travele" +
      "rsService.location\032*.TravelersService.Ge" +
      "tNearbyDriversResponseBY\n%ir.AralStudio." +
      "snapp.Grpc.GrpcServicesB\036TravelersServic" +
      "eImplementationP\001Z\016./GrpcServicesb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TravelersService_GetNearbyDriversResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TravelersService_GetNearbyDriversResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_GetNearbyDriversResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_TravelersService_location_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TravelersService_location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_location_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_TravelersService_user_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TravelersService_user_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_user_descriptor,
        new java.lang.String[] { "Id", "DriverDetails", });
    internal_static_TravelersService_driver_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TravelersService_driver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TravelersService_driver_descriptor,
        new java.lang.String[] { "Name", "Lastname", "VehicleNo", "Balance", "ProfilePic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
